services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=perfit_db
      - POSTGRES_USER=perfit_user
      - POSTGRES_PASSWORD=perfit_password

  web:
    build: .
    command: gunicorn PERFIT.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/PERFIT/static
    expose:
      - 8000
    env_file:
      - ./PERFIT/.env
    depends_on:
      - db

  nginx:
    image: nginx:1.25-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/PERFIT/static
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html  # Pasta compartilhada para validação
    ports:
      - "80:80"
      - "443:443" # Liberamos a porta segura
    depends_on:
      - web

  # Container temporário para gerar/renovar certificados
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx

volumes:
  static_volume:
  postgres_data:
  certbot-etc:
  certbot-var:
  web-root: