services:
  web:
    build: .
    # Comando de Produção: Gunicorn
    command: gunicorn PERFIT.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/PERFIT/static
    expose:
      - 8000
    env_file:
      - ./PERFIT/.env  # <--- CORREÇÃO AQUI: Aponta para a subpasta

  nginx:
    image: nginx:1.25-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/PERFIT/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume: